import { Canvas } from "@react-three/fiber";
import Head from "next/head";
import Hands from "../components/Hands";
import LineHands from "../components/LineHands";

export default function Home() {
  return (
    <div>
      <Head>
        <title>R3FProject</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main id="root">
        <Canvas>
          <LineHands />
        </Canvas>
      </main>
    </div>
  );
}
